import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

/// Centralized Google Fonts helper.
/// Returns a TextStyle from a Google Font name string.
class AppFonts {
  AppFonts._();

  static const String defaultFont = 'Quicksand';

  /// All available font families for theme presets and user selection.
  static const List<String> available = [
    'News Cycle',
    'Karla',
    'Comfortaa',
    'Raleway',
    'Cookie',
    'Yellowtail',
    'Rozha One',
    'Satisfy',
    'Kaushan Script',
    'Economica',
    'Playfair Display SC',
    'Fjalla One',
    'Kanit',
    'PT Sans',
    'Marcellus',
    'Enriqueta',
    'Great Vibes',
    'Sacramento',
    'Playfair Display',
    'Alegreya',
    'Neuton',
    'Marvel',
    'Nunito',
    'Oleo Script',
    'Philosopher',
    'Crimson Text',
    'Noto Serif',
    'Bitter',
    'Spinnaker',
    'Orbitron',
    'Architects Daughter',
    'Signika',
    'Open Sans',
    'Asap',
    'Teko',
    'Merriweather',
    'Varela Round',
    'Abril Fatface',
    'Gilda Display',
    'Quattrocento',
    'Prata',
    'Handlee',
    'Kameron',
    'Allura',
    'Yanone Kaffeesatz',
    'Righteous',
    'Trocchi',
    'Francois One',
    'Patrick Hand',
    'Special Elite',
    'Oswald',
    'Marmelad',
    'Work Sans',
    'Bebas Neue',
    'Dosis',
    'Unna',
    'Linden Hill',
    'Tenor Sans',
    'Lato',
    'Arapey',
    'Federo',
    'Alice',
    'Caveat',
    'Mate',
    'Lora',
    'Petrona',
    'Ubuntu',
    'Nothing You Could Do',
    'Gruppo',
    'Domine',
    'Parisienne',
    'Bangers',
    'Gloria Hallelujah',
    'Chewy',
    'Kalam',
    'Pathway Gothic One',
    'Alfa Slab One',
    'Monoton',
    'Montserrat',
    'Brawler',
    'Indie Flower',
    'Allerta',
    'Six Caps',
    'Rubik',
    'Homemade Apple',
    'Roboto',
    'Unica One',
    'Anton',
    'Josefin Sans',
    'EB Garamond',
    'Courgette',
    'Rock Salt',
    'Monda',
    'Barlow',
    'Permanent Marker',
    'Cabin',
    'Poppins',
    'Rosario',
    'Abel',
    'Ovo',
    'Cormorant Garamond',
    'Judson',
    'Amatic SC',
    'Shadows Into Light',
    'Quicksand',
    'Libre Baskerville',
    'Zilla Slab',
    'Copse',
    'Sigmar One',
    'Fredoka One',
    'Cinzel',
    'Bungee',
    'Tangerine',
    'Pacifico',
    'Habibi',
    'Patua One',
    'Fira Sans',
    'Carter One',
    'Gelasio',
    'Tienne',
    'Rancho',
    'Radley',
    'Vidaloka',
    'Vollkorn',
    'Cantata One',
    'Julius Sans One',
    'Russo One',
    'Lobster Two',
    'Covered By Your Grace',
    'Dancing Script',
    'Grand Hotel',
    'Neucha',
    'Lobster',
    'Syncopate',
  ];

  /// Build a TextStyle from a font name with the given properties.
  /// Falls back to [defaultFont] if the name is not a valid Google Font.
  static TextStyle style(
    String fontName, {
    double fontSize = 26,
    Color? color,
    FontWeight fontWeight = FontWeight.w600,
    double height = 1.4,
    List<Shadow>? shadows,
  }) {
    return safeGetFont(
      fontName,
      fontSize: fontSize,
      color: color,
      fontWeight: fontWeight,
      height: height,
      shadows: shadows,
    );
  }

  /// Safely resolve a Google Font, falling back to [defaultFont].
  static TextStyle safeGetFont(
    String fontName, {
    double? fontSize,
    Color? color,
    FontWeight? fontWeight,
    double? height,
    List<Shadow>? shadows,
  }) {
    try {
      return GoogleFonts.getFont(
        fontName,
        fontSize: fontSize,
        color: color,
        fontWeight: fontWeight,
        height: height,
        shadows: shadows,
      );
    } catch (_) {
      return GoogleFonts.getFont(
        defaultFont,
        fontSize: fontSize,
        color: color,
        fontWeight: fontWeight,
        height: height,
        shadows: shadows,
      );
    }
  }
}
